### ISSUE TITLE
Central Examples Repo

### ISSUE THREAD

**Issue by jmwright** [bragostin/CadQuery-Examples#1]
@bragostin CadQuery also has a central contrib repo if you want to add examples there ever.

https://github.com/CadQuery/cadquery-contrib

With that said, I also have my own repo for CadQuery experiments. If there's something I think is complete and useful enough for the broader community, I normally add it to cadquery-contrib. 

No problem either way, I just wanted to make sure you knew the option was available. Feel free to close this issue.

**Comment by bragostin** [comment]
Done! Thank you for mentioning it, I had forgotten about this possibility.
